# Generated by Django 3.2.7 on 2021-09-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_usa',
            new_name='feels_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='felss_in_world',
        ),
    ]
